export const DATE_STYLES = [
  "bg-green-100 text-green-600",
  "bg-amber-50 text-amber-500",
  "bg-red-100 text-gn-red",
];

export const ANALYSTS = [
  { id: 1, name: "Tom Sherwood", avatar: "/images/table-avatar1.png" },
  { id: 2, name: "Emily Chen", avatar: "/images/table-avatar3.png" },
  { id: 3, name: "James Park", avatar: "/images/table-avatar1.png" },
  { id: 4, name: "Sarah Kim", avatar: "/images/table-avatar3.png" },
  { id: 5, name: "David Lee", avatar: "/images/table-avatar1.png" },
  { id: 6, name: "Anna White", avatar: "/images/table-avatar3.png" },
];

export const UPCOMING_DATES = [
  { id: 1, company: "Pepsico Earnings", type: "Demo", date: "20.03.25" },
  { id: 2, company: "Coca Cola Proxy", type: "Demo", date: "20.03.25" },
  { id: 3, company: "Pepsico Earnings", type: "Demo", date: "20.03.25" },
  { id: 4, company: "Coca Cola Earnings", type: "Demo", date: "20.03.25" },
  { id: 5, company: "Pepsico Earnings", type: "Demo", date: "20.03.25" },
  { id: 6, company: "Pepsico Earnings", type: "Demo", date: "20.03.25" },
  { id: 7, company: "Pepsico Earnings", type: "Demo", date: "20.03.25" },
  { id: 8, company: "Pepsico Earnings", type: "Demo", date: "20.03.25" },
];

export const INITIAL_PROJECTS = [
  { id: 1, name: "Some project name", checked: true },
  { id: 2, name: "Some project name #2", checked: false },
  { id: 3, name: "Awesome project name #3", checked: true },
  { id: 4, name: "Awesome project name #3", checked: false },
  { id: 5, name: "Some project name #2", checked: false },
  { id: 6, name: "Awesome project name #3", checked: false },
  { id: 7, name: "Awesome project name #3", checked: false },
];

export const WEEKLY_TASKS = {
  Mon: [],
  Tue: [],
  Wed: [
    { id: 1, text: "Check Apple stock price" },
    { id: 2, text: "Review Q3 earnings report" },
    { id: 3, text: "Update portfolio allocation" },
  ],
  Thu: [{ id: 4, text: "Check Apple stock price" }],
  Fri: [],
};

export const DAILY_TASKS = {
  25: [
    { id: 1, text: "Check the current Apple stock price and review any major changes" },
    { id: 2, text: "Prepare Q3 earnings summary for Coca-Cola portfolio review" },
    { id: 3, text: "Review ESG compliance checklist for NVIDIA holdings" },
  ],
  26: [
    { id: 1, text: "Analyze Intel foundry progress report and update thesis" },
    { id: 2, text: "Schedule team discussion on semiconductor sector outlook" },
  ],
  27: [
    { id: 1, text: "Review Procter & Gamble organic sales growth data" },
    { id: 2, text: "Update model assumptions for Unilever after FX impact" },
    { id: 3, text: "Prepare weekly summary for Global Equity Income fund" },
    { id: 4, text: "Check Dell server demand backlog numbers" },
  ],
  28: [
    { id: 1, text: "Complete Pepsi earnings preview note before market open" },
  ],
  29: [],
  30: [
    { id: 1, text: "Finalize monthly portfolio rebalancing recommendations" },
    { id: 2, text: "Review Meta advertising revenue trend analysis" },
  ],
};

export const MONTHLY_EVENTS = [8, 14, 19, 30];

export const COVERAGE_DATA = [
  {
    id: 1,
    star: false,
    name: "DELL",
    ticker: "DLL",
    logo: "/images/logos/dell.png",
    sector: "Consumer Staples",
    purchase: "02/24",
    avatar: "/images/table-avatar1.png",
    model: true,
    initialReview: "02/24",
    investThesis: "02/24",
    esgReview: "02/24",
    checklist: "02/24",
    companyMeeting: "02/24",
    spokenToMgt: "02/24",
    teamDiscussion: "02/24",
    quarterlyEarning: "02/24",
  },
  {
    id: 2,
    star: false,
    name: "Intel",
    ticker: "INTL",
    logo: "/images/logos/intel.png",
    sector: "Consumer Staples",
    purchase: "02/24",
    avatar: "/images/table-avatar3.png",
    model: true,
    initialReview: "02/24",
    investThesis: "02/24",
    esgReview: "02/24",
    checklist: "02/24",
    companyMeeting: "02/24",
    spokenToMgt: "02/24",
    teamDiscussion: "02/24",
    quarterlyEarning: "02/24",
  },
  {
    id: 3,
    star: false,
    name: "NVIDIA",
    ticker: "NVDA",
    logo: "/images/logos/nvida.png",
    sector: "Consumer Staples",
    purchase: "02/24",
    avatar: "/images/table-avatar1.png",
    model: true,
    initialReview: "02/24",
    investThesis: "02/24",
    esgReview: "02/24",
    checklist: "02/24",
    companyMeeting: "02/24",
    spokenToMgt: "02/24",
    teamDiscussion: "02/24",
    quarterlyEarning: "02/24",
  },
  {
    id: 4,
    star: false,
    name: "Procter & Gamble",
    ticker: "PG",
    logo: "/images/logos/pg.png",
    sector: "Consumer Staples",
    purchase: "02/24",
    avatar: "/images/table-avatar3.png",
    model: true,
    initialReview: "02/24",
    investThesis: "02/24",
    esgReview: "02/24",
    checklist: "02/24",
    companyMeeting: "02/24",
    spokenToMgt: "02/24",
    teamDiscussion: "02/24",
    quarterlyEarning: "02/24",
  },
  {
    id: 5,
    star: false,
    name: "Mondelez",
    ticker: "MDLZ",
    logo: "/images/logos/mondelez.png",
    sector: "Consumer Staples",
    purchase: "01/24",
    avatar: "/images/table-avatar1.png",
    model: true,
    initialReview: "01/24",
    investThesis: "01/24",
    esgReview: "01/24",
    checklist: "01/24",
    companyMeeting: "01/24",
    spokenToMgt: "01/24",
    teamDiscussion: "01/24",
    quarterlyEarning: "01/24",
  },
  {
    id: 6,
    star: false,
    name: "Coca Cola",
    ticker: "KO",
    logo: "/images/logos/cocacola.png",
    sector: "Consumer Staples",
    purchase: "03/24",
    avatar: "/images/table-avatar3.png",
    model: true,
    initialReview: "03/24",
    investThesis: "03/24",
    esgReview: "03/24",
    checklist: "03/24",
    companyMeeting: "03/24",
    spokenToMgt: "03/24",
    teamDiscussion: "03/24",
    quarterlyEarning: "03/24",
  },
  {
    id: 7,
    star: false,
    name: "Pepsi",
    ticker: "PEP",
    logo: "/images/logos/pepsi.png",
    sector: "Consumer Staples",
    purchase: "02/24",
    avatar: "/images/table-avatar1.png",
    model: false,
    initialReview: "02/24",
    investThesis: "02/24",
    esgReview: "02/24",
    checklist: "02/24",
    companyMeeting: "02/24",
    spokenToMgt: "02/24",
    teamDiscussion: "02/24",
    quarterlyEarning: "02/24",
  },
  {
    id: 8,
    star: false,
    name: "Unilever",
    ticker: "UL",
    logo: "/images/logos/unilever.png",
    sector: "Consumer Staples",
    purchase: "04/24",
    avatar: "/images/table-avatar3.png",
    model: true,
    initialReview: "04/24",
    investThesis: "04/24",
    esgReview: "04/24",
    checklist: "04/24",
    companyMeeting: "04/24",
    spokenToMgt: "04/24",
    teamDiscussion: "04/24",
    quarterlyEarning: "04/24",
  },
  {
    id: 9,
    star: false,
    name: "Meta",
    ticker: "META",
    logo: "/images/logos/meta.png",
    sector: "Technology",
    purchase: "01/24",
    avatar: "/images/table-avatar1.png",
    model: true,
    initialReview: "01/24",
    investThesis: "01/24",
    esgReview: "01/24",
    checklist: "01/24",
    companyMeeting: "01/24",
    spokenToMgt: "01/24",
    teamDiscussion: "01/24",
    quarterlyEarning: "01/24",
  },
  {
    id: 10,
    star: false,
    name: "Auchan",
    ticker: "ACHN",
    logo: "/images/logos/auchan.png",
    sector: "Retail",
    purchase: "03/24",
    avatar: "/images/table-avatar3.png",
    model: false,
    initialReview: "03/24",
    investThesis: "03/24",
    esgReview: "03/24",
    checklist: "03/24",
    companyMeeting: "03/24",
    spokenToMgt: "03/24",
    teamDiscussion: "03/24",
    quarterlyEarning: "03/24",
  },
];

