export const FUND_CATEGORIES = [
  {
    name: "Global Equity Income",
    stocks: [
      { id: "cocacola", name: "Coca Cola", logo: "/images/logos/cocacola.png", ticker: "KO" },
      { id: "danone", name: "Danone SA", logo: "/images/logos/mondelez.png", ticker: "BN" },
      { id: "diageo", name: "Diageo PLC", logo: "/images/logos/pepsi.png", ticker: "DGE" },
      { id: "publicis", name: "Publicis", logo: "/images/logos/pg.png", ticker: "PUB" },
      { id: "mondelez", name: "Mondelez", logo: "/images/logos/mondelez.png", ticker: "MDLZ" },
      { id: "nestle", name: "Nestle SA", logo: "/images/logos/unilever.png", ticker: "NESN" },
      { id: "pepsico", name: "PepsiCo Inc", logo: "/images/logos/pepsi.png", ticker: "PEP" },
      { id: "pg", name: "Procter & Gamble Co", logo: "/images/logos/pg.png", ticker: "PG" },
      { id: "reckitt", name: "Reckitt Benckiser Group", logo: "/images/logos/unilever.png", ticker: "RKT" },
      { id: "unilever", name: "Unilever PLC", logo: "/images/logos/unilever.png", ticker: "UNVR" },
      { id: "aflac", name: "Aflac", logo: "/images/logos/auchan.png", ticker: "AFL" },
      { id: "ajg", name: "Arthur J Gallagher & Co", logo: "/images/logos/iherb.png", ticker: "AJG" },
      { id: "blackrock", name: "BlackRock", logo: "/images/logos/meta.png", ticker: "BLK" },
      { id: "cme", name: "CME Group", logo: "/images/logos/intel.png", ticker: "CME" },
      { id: "pepci", name: "Pepci CO", logo: "/images/logos/pepsi.png", ticker: "PEP" },
      { id: "deutsche", name: "Deutsche Boerse", logo: "/images/logos/dell.png", ticker: "DB1" },
    ],
  },
  {
    name: "GINN",
    stocks: [
      { id: "nvidia", name: "NVIDIA", logo: "/images/logos/nvida.png", ticker: "NVDA" },
      { id: "intel", name: "Intel", logo: "/images/logos/intel.png", ticker: "INTC" },
      { id: "meta-ginn", name: "Meta", logo: "/images/logos/meta.png", ticker: "META" },
    ],
  },
  {
    name: "Legacy Holdings",
    stocks: [
      { id: "dell", name: "Dell Technologies", logo: "/images/logos/dell.png", ticker: "DELL" },
      { id: "telegram", name: "Telegram", logo: "/images/logos/telegram.png", ticker: "TON" },
    ],
  },
  {
    name: "Watchlists",
    stocks: [
      { id: "auchan", name: "Auchan", logo: "/images/logos/auchan.png", ticker: "AUCP" },
      { id: "iherb-w", name: "iHerb", logo: "/images/logos/iherb.png", ticker: "IHRB" },
    ],
  },
];

export const STOCK_DETAILS = {
  cocacola: {
    fullName: "The Coca-Cola Company",
    ticker: "KO",
    logo: "/images/logos/cocacola.png",
    tags: [{ label: "Global Equity Income", color: "blue" }],
    category: "Consumer Staples",
    marketCap: "$257.8 B",
    bought: "March 15, 2021",
    newDate: "March 15, 2021",
    analyst: "Andrew Tamerian",
    thesisSummary: "Coca-Cola remains a dominant force in the global beverage market with unmatched brand recognition and distribution reach. The company has successfully diversified beyond carbonated drinks into water, sports drinks, coffee, and tea. We see continued pricing power driven by strong brand loyalty, alongside efficiency gains from supply chain optimization. The shift towards healthier beverage options and zero-sugar variants is well underway, positioning the company for sustained volume growth in health-conscious markets.",
    coreNotes: [
      { document: "Standard Model", date: "20.03.25", monthSince: "-" },
      { document: "Investment Thesis", date: "20.03.25", monthSince: "-" },
      { document: "Investment Thesis in Charts", date: "20.03.25", monthSince: "-" },
      { document: "Initial Review", date: "20.03.25", monthSince: "-" },
      { document: "ESG Review", date: "20.03.25", monthSince: "-" },
    ],
    earnings: [
      { period: "Q1 24", result: "down", guidance: "up", marketReaction: "flat", guinnessReaction: "flat" },
      { period: "Q3 24", result: "down", guidance: "up", marketReaction: "flat", guinnessReaction: "flat" },
    ],
    stockPrice: {
      price: "$62.45",
      change: "0.85",
      changePercent: "+1.38%",
      sector: "Consumer Staples > Q3, Sept 21, 2025",
      date: "Aug 27, 2025 at 2:00 PM (GMT+11), USD",
    },
  },
  dell: {
    fullName: "Dell Technologies Inc.",
    ticker: "DELL",
    logo: "/images/logos/dell.png",
    tags: [{ label: "Global Equity Income", color: "blue" }, { label: "Legacy Holdings", color: "orange" }],
    category: "Consumer Staples",
    marketCap: "$3.22 T",
    bought: "July 28, 2022",
    newDate: "July 28, 2022",
    analyst: "Andrew Tamerian",
    thesisSummary: "Apple has successfully been shifting their revenue/earnings mix towards Services, a higher quality, higher growth earnings stream. Despite low single digit growth in iPhone, the firm has been executing extremely well in a declining smartphone market – holding unit sales steady and growing the overall installed base (CAGR 10%). This has created a fast-growing end-market in which for Apple to sell 'Services' too (e.g. storage, music etc) – a stickier, less cyclical and higher margin (2x the gross margin than hardware products) business, that now accounts for 37% of earnings. Not only do we expect a continued shift in revenue mix to make what is already a very high quality company, even higher quality, we see a number of growth opportunities for the firm, including continued price increases in iPhone, greater penetration of Subscribers to Services within the installed base, continued market share gains in the installed base (particularly in EMI, and a cyclical upswing in hardware (with products currently in a trough).",
    coreNotes: [
      { document: "Standard Model", date: "20.03.25", monthSince: "-" },
      { document: "Investment Thesis", date: "20.03.25", monthSince: "-" },
      { document: "Investment Thesis in Charts", date: "20.03.25", monthSince: "-" },
      { document: "Initial Review", date: "20.03.25", monthSince: "-" },
      { document: "ESG Review", date: "20.03.25", monthSince: "-" },
    ],
    earnings: [
      { period: "Q1 24", result: "down", guidance: "up", marketReaction: "flat", guinnessReaction: "flat" },
      { period: "Q3 24", result: "down", guidance: "up", marketReaction: "flat", guinnessReaction: "flat" },
    ],
    stockPrice: {
      price: "$130.99",
      change: "2.52",
      changePercent: "+0.79%",
      sector: "Technology Solutions > Q3, Sept 21, 2025",
      date: "Aug 27, 2025 at 2:00 PM (GMT+11), USD",
    },
  },
};

export const DEFAULT_DETAIL = {
  fullName: "Dell Technologies Inc.",
  ticker: "DELL",
  logo: "/images/logos/dell.png",
  tags: [{ label: "Global Equity Income", color: "blue" }, { label: "Legacy Holdings", color: "orange" }],
  category: "Consumer Staples",
  marketCap: "$3.22 T",
  bought: "July 28, 2022",
  newDate: "July 28, 2022",
  analyst: "Andrew Tamerian",
  thesisSummary: "Apple has successfully been shifting their revenue/earnings mix towards Services, a higher quality, higher growth earnings stream. Despite low single digit growth in iPhone, the firm has been executing extremely well in a declining smartphone market – holding unit sales steady and growing the overall installed base (CAGR 10%). This has created a fast-growing end-market in which for Apple to sell 'Services' too (e.g. storage, music etc) – a stickier, less cyclical and higher margin (2x the gross margin than hardware products) business, that now accounts for 37% of earnings. Not only do we expect a continued shift in revenue mix to make what is already a very high quality company, even higher quality, we see a number of growth opportunities for the firm, including continued price increases in iPhone, greater penetration of Subscribers to Services within the installed base, continued market share gains in the installed base (particularly in EMI, and a cyclical upswing in hardware (with products currently in a trough).",
  coreNotes: [
    { document: "Standard Model", date: "20.03.25", monthSince: "-" },
    { document: "Investment Thesis", date: "20.03.25", monthSince: "-" },
    { document: "Investment Thesis in Charts", date: "20.03.25", monthSince: "-" },
    { document: "Initial Review", date: "20.03.25", monthSince: "-" },
    { document: "ESG Review", date: "20.03.25", monthSince: "-" },
  ],
  earnings: [
    { period: "Q1 24", result: "down", guidance: "up", marketReaction: "flat", guinnessReaction: "flat" },
    { period: "Q3 24", result: "down", guidance: "up", marketReaction: "flat", guinnessReaction: "flat" },
  ],
  stockPrice: {
    price: "$130.99",
    change: "2.52",
    changePercent: "+0.79%",
    sector: "Technology Solutions > Q3, Sept 21, 2025",
    date: "Aug 27, 2025 at 2:00 PM (GMT+11), USD",
  },
};

export const CHART_DATA = [
  { date: "Oct 1", price: 102.50 },
  { date: "Oct 3", price: 103.10 },
  { date: "Oct 6", price: 102.80 },
  { date: "Oct 8", price: 104.10 },
  { date: "Oct 10", price: 103.50 },
  { date: "Oct 13", price: 102.20 },
  { date: "Oct 15", price: 101.80 },
  { date: "Oct 17", price: 102.90 },
  { date: "Oct 20", price: 103.30 },
  { date: "Oct 22", price: 103.60, report: true },
  { date: "Oct 24", price: 104.80 },
  { date: "Oct 27", price: 105.10 },
  { date: "Oct 29", price: 105.20 },
  { date: "Oct 31", price: 106.40 },
  { date: "Nov 3", price: 106.90 },
  { date: "Nov 5", price: 107.30 },
  { date: "Nov 7", price: 106.50 },
  { date: "Nov 10", price: 105.80 },
  { date: "Nov 12", price: 104.90 },
  { date: "Nov 14", price: 105.60 },
  { date: "Nov 17", price: 106.20 },
  { date: "Nov 19", price: 106.10, report: true },
  { date: "Nov 21", price: 105.30 },
  { date: "Nov 24", price: 104.10 },
  { date: "Nov 26", price: 103.40 },
  { date: "Nov 28", price: 102.80 },
  { date: "Dec 1", price: 102.10 },
  { date: "Dec 3", price: 101.20 },
  { date: "Dec 5", price: 100.60 },
  { date: "Dec 8", price: 101.30 },
  { date: "Dec 10", price: 99.80 },
  { date: "Dec 12", price: 99.20 },
  { date: "Dec 15", price: 98.90 },
  { date: "Dec 17", price: 98.50 },
  { date: "Dec 19", price: 97.80 },
  { date: "Dec 22", price: 97.50 },
  { date: "Dec 24", price: 97.30 },
  { date: "Dec 29", price: 98.10 },
  { date: "Dec 31", price: 99.10 },
  { date: "Jan 2", price: 98.40 },
  { date: "Jan 6", price: 97.90 },
  { date: "Jan 7", price: 97.60 },
  { date: "Jan 9", price: 97.20 },
  { date: "Jan 13", price: 96.80 },
  { date: "Jan 14", price: 96.40, report: true },
  { date: "Jan 16", price: 97.10 },
  { date: "Jan 20", price: 97.80 },
  { date: "Jan 21", price: 98.20 },
  { date: "Jan 23", price: 97.90 },
  { date: "Jan 27", price: 97.40 },
  { date: "Jan 28", price: 97.10 },
  { date: "Jan 30", price: 98.00 },
  { date: "Feb 3", price: 98.80 },
  { date: "Feb 4", price: 99.50 },
  { date: "Feb 6", price: 99.90 },
  { date: "Feb 10", price: 100.40 },
  { date: "Feb 11", price: 100.80 },
  { date: "Feb 13", price: 100.20 },
  { date: "Feb 17", price: 99.60 },
  { date: "Feb 18", price: 98.90 },
  { date: "Feb 20", price: 99.10 },
  { date: "Feb 24", price: 99.40 },
  { date: "Feb 25", price: 99.30 },
  { date: "Feb 27", price: 98.60 },
  { date: "Mar 3", price: 97.80 },
  { date: "Mar 4", price: 97.20 },
  { date: "Mar 6", price: 96.50 },
  { date: "Mar 10", price: 96.10 },
  { date: "Mar 11", price: 95.60 },
  { date: "Mar 13", price: 95.10 },
  { date: "Mar 17", price: 94.80 },
  { date: "Mar 18", price: 94.50, report: true },
  { date: "Mar 20", price: 95.20 },
  { date: "Mar 24", price: 95.80 },
  { date: "Mar 25", price: 96.10 },
  { date: "Mar 27", price: 95.70 },
  { date: "Mar 31", price: 95.40 },
  { date: "Apr 1", price: 95.30 },
  { date: "Apr 3", price: 95.90 },
  { date: "Apr 7", price: 96.60 },
  { date: "Apr 8", price: 97.80 },
  { date: "Apr 10", price: 98.30 },
  { date: "Apr 14", price: 98.90 },
  { date: "Apr 15", price: 99.40 },
  { date: "Apr 17", price: 100.10 },
  { date: "Apr 21", price: 100.80 },
  { date: "Apr 22", price: 101.20 },
  { date: "Apr 24", price: 100.90 },
  { date: "Apr 28", price: 100.60 },
  { date: "Apr 29", price: 100.50 },
  { date: "May 1", price: 101.40 },
  { date: "May 5", price: 102.60 },
  { date: "May 6", price: 103.80 },
  { date: "May 8", price: 105.10 },
  { date: "May 12", price: 107.40 },
  { date: "May 13", price: 108.20 },
  { date: "May 15", price: 110.60 },
  { date: "May 19", price: 112.80 },
  { date: "May 21", price: 114.52, report: true },
  { date: "May 22", price: 113.10 },
  { date: "May 27", price: 110.30 },
  { date: "May 29", price: 109.10 },
  { date: "Jun 2", price: 108.20 },
  { date: "Jun 3", price: 107.60 },
  { date: "Jun 5", price: 106.80 },
  { date: "Jun 9", price: 106.10 },
  { date: "Jun 10", price: 105.40 },
  { date: "Jun 12", price: 104.80 },
  { date: "Jun 16", price: 104.20 },
  { date: "Jun 17", price: 103.90 },
  { date: "Jun 19", price: 104.50 },
  { date: "Jun 23", price: 105.60 },
  { date: "Jun 24", price: 106.20 },
  { date: "Jun 26", price: 107.10 },
  { date: "Jun 30", price: 107.90 },
  { date: "Jul 1", price: 108.50 },
  { date: "Jul 3", price: 109.30 },
  { date: "Jul 7", price: 110.10 },
  { date: "Jul 8", price: 110.70, report: true },
  { date: "Jul 10", price: 110.20 },
  { date: "Jul 14", price: 109.60 },
  { date: "Jul 15", price: 109.30 },
  { date: "Jul 17", price: 110.10 },
  { date: "Jul 21", price: 111.20 },
  { date: "Jul 22", price: 111.80 },
  { date: "Jul 24", price: 112.50 },
  { date: "Jul 28", price: 113.10 },
  { date: "Jul 29", price: 113.40 },
  { date: "Jul 31", price: 112.80 },
  { date: "Aug 4", price: 112.30 },
  { date: "Aug 5", price: 112.10 },
  { date: "Aug 7", price: 112.90 },
  { date: "Aug 11", price: 113.80 },
  { date: "Aug 12", price: 114.60 },
  { date: "Aug 14", price: 115.20 },
  { date: "Aug 18", price: 115.80 },
  { date: "Aug 19", price: 116.20, report: true },
  { date: "Aug 21", price: 115.90 },
  { date: "Aug 25", price: 115.60 },
  { date: "Aug 26", price: 115.50 },
  { date: "Aug 28", price: 116.10 },
  { date: "Sep 1", price: 116.80 },
  { date: "Sep 2", price: 117.30 },
  { date: "Sep 4", price: 116.90 },
  { date: "Sep 8", price: 116.60 },
  { date: "Sep 9", price: 116.80 },
  { date: "Sep 11", price: 117.20 },
  { date: "Sep 15", price: 117.60 },
  { date: "Sep 16", price: 117.99 },
];
